---
  - name: Fetch imagestream {{ react_infra_name }}:{{ version }}
    set_fact: 
      imagestreamtag: "{{ lookup('k8s', kind='ImageStreamTag', namespace=tools_namespace, resource_name=react_infra_name + ':' + version) }}"
  - debug: 
      msg: 
        - Image Tag {{ version }} does not exist in {{ tools_namespace }}. 
        - This is because either you have not run ansible-playbook build-react.yaml -e PR={{ PR }}
        - Or the buildconfig has been run but isn't complete
        - OR the build failed
    when: "imagestreamtag|length == 0"
