---
  - name: Get PR author response for PR {{ PR }}
    uri:
      url: https://api.github.com/repos/{{ github_owner }}/{{ github_repo }}/pulls/{{ PR }}
      method: GET
    register: pr_request
    set_fact:
      is_valid_author: true

  - name: Set PR author for PR {{ PR }}
    set_fact: 
      pr_author: "{{ pr_request.json.user.login }}"
    when:
      - is_valid_author
  
  - name: Check if PR author {{ pr_author }} for PR {{ PR }} is one of the collaborators in {{ github_owner }}/{{ github_repo }}
    uri:
      url: https://api.github.com/repos/{{ github_owner }}/{{ github_repo }}/collaborators/{{ pr_author }}
      method: GET
      headers: 
        Authorization: "Token {{ GITHUB_TOKEN }}"
      status_code: 204, 404
    register: collaborator_response
    when: 
      - is_valid_author
      
  - name: Check for valid collaborator_response
    set_fact:
      is_valid_author: "{% if collaborator_response.status == 204 %}true{% else %}false{% endif %}"
      when: 
        - is_valid_author 
