---
  - hosts: localhost
    gather_facts: no
    vars:
      dev_image_tag: "{{ lookup('template', './templates/pr_tag.j2') }}"
      image_namespace: "{{ tools_namespace }}"
      gh_env: "{{ github_environments[ENV] }}"
      namespace: "{% if 'prod' in gh_env %}{{ prod_namespace }}{% elif 'test' in gh_env %}{{ test_namespace }}{% elif 'dev' in gh_env %}{{ dev_namespace }}{% endif %}"
      # in test and prod namespaces they only house one tag: prod | test
      new_image_tag: "{% if 'prod' in gh_env %}{{ prod_image_tag }}{% elif 'test' in gh_env %}{{ test_image_tag }}{% elif 'dev' in gh_env %}{{ dev_image_tag }}{% endif %}"
      suffix: "{{ new_image_tag }}"
      version: "{{ new_image_tag }}"
      infra_name: "{{ react_infra_name }}"
    tasks:
      - name: Pre checks
        include: ./tasks/check_pr_exists.yaml

      - name: Check if valid author
        include: ./tasks/check_if_valid_pr_author.yaml

      - name: Check if should build 
        include: ./tasks/check_if_should_build.yaml
        when: is_valid_author

      - debug:
          msg:
            - not rebuilding react project, the commits match
        when: not should_build

      - name: Build React Project
        include: ./tasks/build_react.yaml
        when: 
          - should_build
          - is_valid_author

      - name: Wait for build to complete
        include: ./tasks/wait_for_build_to_complete.yaml



