---
  - hosts: localhost
    vars:
      dev_image_tag: "{{ lookup('template', './templates/pr_tag.j2') }}"
      gh_env: "{{ github_environments[ENV] }}"
      namespace: "{% if 'prod' in gh_env %}{{ prod_namespace }}{% elif 'test' in gh_env %}{{ test_namespace }}{% elif 'dev' in gh_env %}{{ dev_namespace }}{% endif %}"
      # in test and prod namespaces they only house one tag: prod | test
      new_image_tag: "{% if 'prod' in gh_env %}{{ prod_image_tag }}{% elif 'test' in gh_env %}{{ test_image_tag }}{% elif 'dev' in gh_env %}{{ dev_image_tag }}{% endif %}"
      suffix: "{{ new_image_tag }}"
      version: "{{ new_image_tag }}"
      image_namespace: "{{ tools_namespace }}"
      infra_name: "{{ strapi_infra_name }}"
    tasks:
      - name: check images
        include: ./tasks/check_image_exists-test-prod.yaml
      - name: Deploying to test/prod
        include: ./tasks/deploy_strapi_dev_test_prod.yaml