name: Deploy React to Test/Prod
on: 
  workflow_dispatch:
    inputs:
      prnumber:
        description: 'Pull Request number'     
        required: true
      environment:
        required: true
        default: 'test'
        description: 'Deploy environment'
jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Store PR Num in env
      uses: actions/github-script@v3
      with:
        github-token: ${{github.token}}
        script: |
          const prNumber = ${{ github.event.inputs.prnumber }};
          core.exportVariable('PULL_NUMBER', prNumber);
          const env = "${{ github.event.inputs.environment }}";
          core.exportVariable('ENV', env);
    - name: install oc
      run: |
        curl -O https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.1/openshift-client-linux.tar.gz > oc.tar.gz
        tar xvzf oc.tar.gz 
        ls -l
        sudo mv oc /usr/local/bin
        rm oc.tar.gz
        oc version
        pip install openshift
    - name: Check user permissions for admin
      id: check
      uses: scherermichael-oss/action-has-permission@master
      with:
        required-permission: admin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Cancel workflow if user does NOT have sufficient permissions
      if: "! steps.check.outputs.has-permission"
      run: exit 1
    - name: login to oc client
      run: ansible-playbook ansible/oc-login.yaml -e OPENSHIFT_SERVER_URL=${{ secrets.OPENSHIFT_SERVER_URL_OC4 }} -e CICD_SA_ACCOUNT_TOKEN=${{ secrets.CICD_SA_ACCOUNT_TOKEN_OC4 }}
    - name: build react app
      run: ansible-playbook ansible/build-react-for-test-prod.yaml -e PR=$PULL_NUMBER -e ENV=$ENV -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v
    - name: deploy react app
      run: ansible-playbook ansible/deploy-react-to-test-prod.yaml -e PR=$PULL_NUMBER -e ENV=$ENV -v
    - name: create github deployment to test/prod
      run: ansible-playbook ansible/create-gh-deployment.yaml -e PR=$PULL_NUMBER -e ENV=$ENV -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -e OPENSHIFT_SERVER_URL=${{ secrets.OPENSHIFT_SERVER_URL_OC4 }} -v

    
